### PR TITLE
microsoft/auth: Use new Azure authentication logic

### PR DESCRIPTION
**Pull request by holygeek**
The new authentication returns a token that expires after 10 minutes.
The changes here requests a new token after 8 minutes.

References:
http://docs.microsofttranslator.com/oauth-token.html
http://docs.microsofttranslator.com/text-translate.html

### CODE REVIEW

**Comment by holygeek** [comment]
The Travis CI tests failed at "go get"-ing the "go vet" tool [1]. The test environment seems to be outdated?

https://travis-ci.org/st3v/translator/jobs/229891136

**Comment by st3v** [comment]
Thanks for the PR. Did you run the tests locally? I'm seeing the following errors...

```
± |holygeek-master ✓| → go test ./...
ok  	github.com/st3v/translator	0.052s
?   	github.com/st3v/translator/example	[no test files]
ok  	github.com/st3v/translator/google	0.044s
ok  	github.com/st3v/translator/http	0.047s
--- FAIL: TestRouterAuthURL (0.00s)
	router_test.go:13: Unexpected AuthURL. Want: 'https://datamarket.accesscontrol.windows.net/v2/OAuth2-13'. Got: 'https://api.cognitive.microsoft.com/sts/v1.0/issueToken'.
--- FAIL: TestRouterTranslationURL (0.00s)
	router_test.go:25: Unexpected AuthURL. Want: 'http://api.microsofttranslator.com/v2/Http.svc/Translate'. Got: 'https://api.microsofttranslator.com/v2/Http.svc/Translate'.
--- FAIL: TestRouterLanguageNamesURL (0.00s)
	router_test.go:37: Unexpected AuthURL. Want: 'http://api.microsofttranslator.com/v2/Http.svc/GetLanguageNames'. Got: 'https://api.microsofttranslator.com/v2/Http.svc/GetLanguageNames'.
--- FAIL: TestRouterLanguageCodesURL (0.00s)
	router_test.go:49: Unexpected AuthURL. Want: 'http://api.microsofttranslator.com/v2/Http.svc/GetLanguagesForTranslate'. Got: 'https://api.microsofttranslator.com/v2/Http.svc/GetLanguagesForTranslate'.
FAIL
FAIL	github.com/st3v/translator/microsoft	0.054s
--- FAIL: TestAccessTokenProviderRefreshToken (0.00s)
	access_token_provider_test.go:26: Unexpected client_id '' in post request.
	access_token_provider_test.go:58: Unexpected error returned by requestAccessToken: Post http://127.0.0.1:57459: EOF
		  at (*accessTokenProvider).RefreshToken (github.com/st3v/translator/microsoft/auth/access_token_provider.go:40)
		  at TestAccessTokenProviderRefreshToken (github.com/st3v/translator/microsoft/auth/access_token_provider_test.go:57)
		  at tRunner (testing/testing.go:611)
		  at goexit (runtime/asm_amd64.s:2087)
FAIL
FAIL	github.com/st3v/translator/microsoft/auth	0.020s
```

**Comment by st3v** [comment]
Never mind, I merged this and fixed the unit tests for you. ;)

I also did some cleanup, mainly to update the docs and remove the notion of clientID and clientSecret. Take a look at https://github.com/st3v/translator/commit/d13056a5929704f264d21b102987311c0f379fc3.

**Comment by holygeek** [comment]
Ah, thanks. Yep, I ran only "go test", not "go test ./..." so I didn't notice the failures in the auth package. I fixed it up and did a push -f to my branch before I read your latest message (note to self: read latest github notifications before doing changes), so I reverted my branch back to its old state.

I knew that the change would require more deletions in other places so I'm glad that you went ahead and did it for me :)

**Comment by st3v** [comment]
No worries. Thanks for the contribution.

**Pull request merged**
